import AcademyHeader from "@/components/AcademyHeader";
import { trpc } from "@/lib/trpc";
import { ArrowRight, Search } from "lucide-react";
import { useMemo, useState } from "react";
import { Link } from "wouter";

export default function Blog() {
  const { data: posts = [], isLoading } = trpc.academy.getBlogPosts.useQuery();
  const [query, setQuery] = useState("");
  const [category, setCategory] = useState("All");
  const categories = useMemo(() => ["All", ...Array.from(new Set(posts.map((post) => post.category)))], [posts]);
  const filtered = posts.filter((post) => (category === "All" || post.category === category) && `${post.title} ${post.summary ?? ""}`.toLowerCase().includes(query.toLowerCase()));
  return <div className="min-h-screen bg-[#fbfcf7]"><AcademyHeader /><main className="container py-14 sm:py-20"><div className="max-w-3xl"><div className="font-mono-brand text-xs uppercase tracking-[0.18em] text-[#2c7e7c]">BuduTech notes</div><h1 className="mt-4 font-display text-5xl leading-[1] tracking-[-0.05em] text-[#163c3e] sm:text-6xl">Useful thinking for <em className="text-[#2c7e7c]">digital builders.</em></h1><p className="mt-5 text-lg leading-8 text-[#607a7c]">Ideas, patterns, and practical guides around websites, AI, entrepreneurship, and digital work.</p></div><div className="mt-12 flex flex-col gap-4 border-y border-[#dce5d9] py-5 lg:flex-row lg:items-center lg:justify-between"><div className="flex flex-wrap gap-2">{categories.map((item) => <button key={item} onClick={() => setCategory(item)} className={`rounded-full px-4 py-2 text-sm font-medium ${item === category ? "bg-[#123a3c] text-white" : "bg-[#edf4ed] text-[#557174]"}`}>{item}</button>)}</div><label className="flex items-center gap-2 rounded-xl border border-[#ceded2] bg-white px-3 py-2.5 lg:w-72"><Search className="h-4 w-4 text-[#6b898b]" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search notes" className="w-full bg-transparent text-sm outline-none" /></label></div><div className="mt-9 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{isLoading ? <p className="text-[#607a7c]">Loading resources…</p> : filtered.length ? filtered.map((post) => <Link href={`/blog/${post.slug}`} key={post.id} className="group rounded-3xl border border-[#dce5d9] bg-white p-6 soft-shadow"><div className="font-mono-brand text-[0.65rem] uppercase tracking-[0.17em] text-[#2c7e7c]">{post.category}</div><h2 className="mt-5 text-2xl font-semibold leading-[1.1] tracking-[-0.04em] text-[#163c3e]">{post.title}</h2><p className="mt-3 line-clamp-3 leading-6 text-[#607a7c]">{post.summary}</p><div className="mt-7 inline-flex items-center text-sm font-semibold text-[#216c6d]">Read note <ArrowRight className="ml-1.5 h-4 w-4 transition-transform group-hover:translate-x-1" /></div></Link>) : <div className="col-span-full rounded-3xl border border-dashed border-[#cbdacb] bg-white p-10 text-center text-[#607a7c]">No notes match that search yet.</div>}</div></main></div>;
}
