import AcademyHeader from "@/components/AcademyHeader";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { Award, Download, ShieldCheck } from "lucide-react";
import { Link, useRoute } from "wouter";

export default function CertificateView() {
  const [, params] = useRoute("/certificates/:code");
  const { data, isLoading, error } = trpc.academy.getCertificate.useQuery({ code: params?.code ?? "" }, { enabled: Boolean(params?.code) });
  return <div className="min-h-screen bg-[#fbfcf7]"><AcademyHeader /><main className="container py-12 sm:py-20">{isLoading ? <div className="text-center text-[#607a7c]">Verifying certificate…</div> : error || !data ? <div className="mx-auto max-w-xl rounded-3xl border border-[#dbe6dc] bg-white p-8 text-center"><ShieldCheck className="mx-auto h-8 w-8 text-[#9aaaab]" /><h1 className="mt-4 font-display text-4xl text-[#163c3e]">Certificate not found.</h1><p className="mt-3 leading-7 text-[#607a7c]">Check the verification code and try again.</p><Link href="/courses"><Button className="mt-6 bg-[#123a3c] text-white">Explore Academy courses</Button></Link></div> : <><div id="certificate" className="mx-auto max-w-4xl overflow-hidden rounded-[2rem] border-[10px] border-[#123a3c] bg-[#f9f8ee] p-7 text-center shadow-2xl sm:p-14"><div className="mx-auto grid h-14 w-14 place-items-center rounded-full bg-[#d4f36b] text-[#123a3c]"><Award className="h-7 w-7" /></div><div className="mt-6 font-mono-brand text-xs uppercase tracking-[0.25em] text-[#2c7e7c]">BuduTech Academy</div><h1 className="mt-7 font-display text-5xl tracking-[-0.045em] text-[#163c3e] sm:text-6xl">Certificate of completion</h1><p className="mt-8 text-[#607a7c]">This confirms that</p><div className="mt-3 font-display text-4xl text-[#2c7e7c] sm:text-5xl">{data.studentName}</div><p className="mt-8 text-[#607a7c]">has completed the Academy program</p><div className="mt-3 text-2xl font-semibold tracking-[-0.035em] text-[#163c3e]">{data.courseTitle}</div><div className="mt-12 flex flex-col justify-between gap-4 border-t border-[#d9dfca] pt-5 text-sm text-[#557174] sm:flex-row"><span>Issued {new Date(data.issuedAt).toLocaleDateString(undefined, { dateStyle: "long" })}</span><span className="font-mono-brand text-xs text-[#2c7e7c]">Verification: {data.code}</span></div></div><div className="mx-auto mt-6 flex max-w-4xl justify-center"><Button onClick={() => window.print()} className="bg-[#123a3c] text-white hover:bg-[#214f50]"><Download className="mr-2 h-4 w-4" />Print or save certificate</Button></div></>}</main></div>;
}
