import { useAuth } from "@/_core/hooks/useAuth";
import AcademyHeader from "@/components/AcademyHeader";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { CheckCircle2, ChevronDown, Clock3, GraduationCap, PlayCircle } from "lucide-react";
import { useState } from "react";
import { Link, useRoute } from "wouter";
import { toast } from "sonner";

export default function CourseDetail() {
  const [, params] = useRoute("/courses/:slug");
  const { data, isLoading, error } = trpc.academy.getCourseBySlug.useQuery({ slug: params?.slug ?? "" }, { enabled: Boolean(params?.slug) });
  const { isAuthenticated } = useAuth();
  const utils = trpc.useUtils();
  const [openModule, setOpenModule] = useState<number | null>(null);
  const enroll = trpc.academy.enrollFreeCourse.useMutation({ onSuccess: () => { toast.success("You are enrolled. Your course is ready in the dashboard."); utils.academy.getStudentDashboard.invalidate(); } });
  const checkout = trpc.academy.startPaidCourseCheckout.useMutation({ onSuccess: (result) => { if (result.alreadyEnrolled) { toast.success("You already have access to this course."); window.location.assign("/dashboard"); return; } if (result.authorizationUrl) window.location.assign(result.authorizationUrl); } });

  if (isLoading) return <div className="min-h-screen bg-[#fbfcf7]"><AcademyHeader /><main className="container py-20 text-[#607a7c]">Loading course details…</main></div>;
  if (error || !data) return <div className="min-h-screen bg-[#fbfcf7]"><AcademyHeader /><main className="container py-20"><h1 className="font-display text-4xl">This course is not currently available.</h1><Link href="/courses"><Button className="mt-6">Back to courses</Button></Link></main></div>;

  const { course, modules, lessons } = data;
  const isFree = Number(course.price) === 0;
  const action = () => { if (!isAuthenticated) { window.location.assign("/register"); return; } if (isFree) enroll.mutate({ courseId: course.id }); else checkout.mutate({ courseId: course.id }); };
  const actionLabel = enroll.isPending ? "Enrolling…" : checkout.isPending ? "Opening secure checkout…" : isFree ? "Start learning free" : "Pay securely with Paystack";

  return <div className="min-h-screen bg-[#fbfcf7]"><AcademyHeader /><main>
    <section className="bg-[#123a3c] py-16 text-white sm:py-24"><div className="container grid gap-10 lg:grid-cols-[1fr_.68fr] lg:items-end"><div><Link href="/courses" className="font-mono-brand text-xs uppercase tracking-[0.18em] text-[#d4f36b]">← Academy catalogue</Link><div className="mt-6 inline-flex rounded-full bg-white/10 px-3 py-1 text-xs font-semibold text-[#d7eea1]">{course.category}</div><h1 className="mt-5 max-w-3xl font-display text-5xl leading-[0.98] tracking-[-0.055em] sm:text-6xl">{course.title}</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-white/70">{course.description ?? course.shortDescription ?? course.tagline}</p><div className="mt-7 flex flex-wrap gap-5 text-sm text-white/75"><span className="inline-flex items-center gap-2"><GraduationCap className="h-4 w-4 text-[#d4f36b]" />{course.level}</span><span className="inline-flex items-center gap-2"><Clock3 className="h-4 w-4 text-[#d4f36b]" />{lessons.reduce((sum, lesson) => sum + lesson.durationMinutes, 0)} minutes</span><span className="inline-flex items-center gap-2"><PlayCircle className="h-4 w-4 text-[#d4f36b]" />{lessons.length} lessons</span></div></div><div className="rounded-3xl border border-white/10 bg-white/[0.07] p-6"><div className="font-mono-brand text-xs uppercase tracking-[0.17em] text-[#d4f36b]">{isFree ? "Free Academy program" : "Paid Academy program"}</div><div className="mt-3 text-3xl font-semibold">{isFree ? "Free access" : `₦${Number(course.price).toLocaleString()}`}</div><p className="mt-2 text-sm leading-6 text-white/60">{isFree ? "Create your student account and begin the program when you are ready." : "Pay securely with Paystack. Access unlocks only after server-side verification."}</p><Button onClick={action} disabled={enroll.isPending || checkout.isPending} className="mt-6 h-12 w-full bg-[#d4f36b] text-[#123a3c] hover:bg-[#c7e85c]">{actionLabel}</Button><div className="mt-5 space-y-2 text-sm text-white/70"><span className="flex gap-2"><CheckCircle2 className="h-4 w-4 shrink-0 text-[#d4f36b]" />Structured, beginner-friendly lessons</span><span className="flex gap-2"><CheckCircle2 className="h-4 w-4 shrink-0 text-[#d4f36b]" />Progress saved to your student dashboard</span></div></div></div></section>
    <section className="container py-16 sm:py-20"><div className="grid gap-12 lg:grid-cols-[.72fr_1.28fr]"><aside><div className="font-mono-brand text-xs uppercase tracking-[0.18em] text-[#2c7e7c]">Course structure</div><h2 className="mt-3 font-display text-4xl leading-tight tracking-[-0.045em] text-[#163c3e]">A clear way from first lesson to finished work.</h2><p className="mt-4 leading-7 text-[#607a7c]">Learn in focused modules, return whenever you need, and see your completion move forward as you go.</p></aside><div className="overflow-hidden rounded-3xl border border-[#d9e4da] bg-white">{modules.length ? modules.map((module, index) => { const isOpen = openModule === module.id; const moduleLessons = lessons.filter((lesson) => lesson.moduleId === module.id); return <div className="border-b border-[#e2ebe2] last:border-0" key={module.id}><button onClick={() => setOpenModule(isOpen ? null : module.id)} className="flex w-full items-center gap-4 px-5 py-5 text-left sm:px-6"><span className="font-mono-brand text-sm text-[#2c7e7c]">{String(index + 1).padStart(2, "0")}</span><span className="flex-1 text-lg font-semibold tracking-[-0.025em] text-[#163c3e]">{module.title}</span><span className="mr-3 text-sm text-[#779295]">{moduleLessons.length} lessons</span><ChevronDown className={`h-5 w-5 text-[#527577] transition-transform ${isOpen ? "rotate-180" : ""}`} /></button>{isOpen && <div className="bg-[#f5f9f3] px-5 pb-5 sm:px-6">{moduleLessons.map((lesson) => <div key={lesson.id} className="flex items-center gap-3 border-t border-[#dde8de] py-3.5 text-sm"><PlayCircle className="h-4 w-4 text-[#2c7e7c]" /><span className="flex-1 font-medium text-[#294c4e]">{lesson.title}</span><span className="text-[#779295]">{lesson.durationMinutes} min</span></div>)}</div>}</div>; }) : <div className="p-6 text-[#6b8587]">The curriculum is being organized and will appear here when it is published.</div>}</div></div></section>
  </main></div>;
}
