import { useAuth } from "@/_core/hooks/useAuth";
import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { startLogin } from "@/const";
import { trpc } from "@/lib/trpc";
import { Award, CalendarClock, CheckCircle2, Copy, ExternalLink, Link2, PlayCircle, Share2, Trophy } from "lucide-react";
import { Link } from "wouter";
import { toast } from "sonner";

function Metric({ value, label }: { value: string | number; label: string }) {
  return <div className="rounded-2xl bg-white/10 p-4"><div className="font-mono-brand text-2xl text-[#d4f36b]">{value}</div><div className="mt-1 text-xs text-white/55">{label}</div></div>;
}

export default function Dashboard() {
  const { isAuthenticated, loading } = useAuth();
  const { data, isLoading } = trpc.academy.getStudentDashboard.useQuery(undefined, { enabled: isAuthenticated });
  const utils = trpc.useUtils();
  const register = trpc.academy.registerForActiveEvent.useMutation({ onSuccess: () => { toast.success("Your place is confirmed."); utils.academy.getStudentDashboard.invalidate(); utils.academy.getHomeData.invalidate(); } });
  const referralUrl = data?.referral.url ? `${window.location.origin}${data.referral.url}` : "";
  const copy = async () => { if (!referralUrl) return; await navigator.clipboard.writeText(referralUrl); toast.success("Referral link copied."); };
  const share = async () => { if (!referralUrl) return; if (navigator.share) await navigator.share({ title: "Join me at BuduTech Academy", text: "I’m learning practical digital skills with BuduTech Academy. Join the free training with my link.", url: referralUrl }); else await copy(); };

  if (loading || (isAuthenticated && isLoading)) return <div className="grid min-h-screen place-items-center bg-[#fbfcf7] text-[#607a7c]">Loading your Academy…</div>;
  if (!isAuthenticated) return <div className="grid min-h-screen place-items-center bg-[#fbfcf7] p-6"><div className="max-w-md rounded-3xl border border-[#dbe6dc] bg-white p-8 text-center academy-shadow"><div className="font-mono-brand text-xs uppercase tracking-[0.18em] text-[#2c7e7c]">Student dashboard</div><h1 className="mt-4 font-display text-4xl tracking-[-0.045em] text-[#163c3e]">Sign in to continue learning.</h1><p className="mt-4 leading-7 text-[#607a7c]">Your courses, event registration, certificates, and referral tools are protected in one place.</p><Button onClick={startLogin} className="mt-6 bg-[#123a3c] text-white hover:bg-[#214f50]">Secure sign-in</Button></div></div>;

  return <DashboardLayout><div className="mx-auto max-w-6xl space-y-8">
    <section className="rounded-[2rem] bg-[#123a3c] p-6 text-white sm:p-8"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><div className="font-mono-brand text-xs uppercase tracking-[0.18em] text-[#d4f36b]">Your learning space</div><h1 className="mt-3 font-display text-4xl leading-tight tracking-[-0.045em] sm:text-5xl">Welcome back, {data?.user.name?.split(" ")[0] ?? "student"}.</h1><p className="mt-3 max-w-xl text-white/65">Small, consistent steps are how useful skills start to compound.</p></div><Link href="/courses"><Button className="bg-[#d4f36b] text-[#123a3c] hover:bg-[#c7e85c]">Explore courses</Button></Link></div></section>
    <section className="grid gap-5 lg:grid-cols-[1.3fr_.7fr]"><div className="rounded-3xl border border-[#dbe6dc] bg-white p-6 soft-shadow"><div className="flex items-center justify-between"><div><div className="font-mono-brand text-xs uppercase tracking-[0.16em] text-[#2c7e7c]">Continue learning</div><h2 className="mt-2 text-2xl font-semibold tracking-[-0.04em] text-[#163c3e]">Your enrolled programs</h2></div><PlayCircle className="h-8 w-8 text-[#2c7e7c]" /></div><div className="mt-6 space-y-4">{data?.courseProgress.length ? data.courseProgress.map(({ course, firstLessonId, percent, completedLessons, totalLessons }) => <Link href={firstLessonId ? `/learn/${course.id}/${firstLessonId}` : `/courses/${course.slug}`} key={course.id} className="block rounded-2xl border border-[#e1ebe2] p-4 transition-colors hover:bg-[#f6faf4]"><div className="flex gap-4"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#e9f5d0] text-[#245b5b]"><PlayCircle className="h-5 w-5" /></div><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-3"><span className="truncate font-semibold text-[#173d3f]">{course.title}</span><span className="text-sm font-semibold text-[#2b7070]">{percent}%</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-[#e5eee6]"><div className="h-full rounded-full bg-[#2c7e7c]" style={{ width: `${percent}%` }} /></div><div className="mt-2 text-xs text-[#758f90]">{completedLessons} of {totalLessons} lessons complete</div></div></div></Link>) : <div className="rounded-2xl bg-[#f5f9f3] p-5 text-sm leading-6 text-[#607a7c]">You have not enrolled in a course yet. Your next useful step is waiting in the Academy catalogue.</div>}</div></div><div className="rounded-3xl border border-[#dbe6dc] bg-[#f0f7ed] p-6"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#d4f36b] text-[#123a3c]"><CalendarClock className="h-5 w-5" /></span><div><div className="text-sm font-semibold text-[#173d3f]">Upcoming live training</div><div className="text-xs text-[#6c8587]">Campaign access</div></div></div>{data?.activeEvent ? <><h3 className="mt-6 text-xl font-semibold leading-tight tracking-[-0.035em] text-[#173d3f]">{data.activeEvent.title}</h3><p className="mt-3 text-sm leading-6 text-[#607a7c]">{new Date(data.activeEvent.startDate).toLocaleString(undefined, { dateStyle: "medium", timeStyle: "short" })}</p>{data.activeEvent.registered ? <div className="mt-6 flex items-center gap-2 text-sm font-semibold text-[#2b7070]"><CheckCircle2 className="h-4 w-4" />Your place is confirmed</div> : <Button onClick={() => register.mutate()} disabled={register.isPending} className="mt-6 w-full bg-[#123a3c] text-white hover:bg-[#214f50]">{register.isPending ? "Confirming…" : "Reserve my free seat"}</Button>}</> : <p className="mt-6 text-sm leading-6 text-[#607a7c]">The next Academy event will appear here when it is active.</p>}</div></section>
    <section className="grid gap-5 lg:grid-cols-[1.05fr_.95fr]"><div className="rounded-3xl border border-[#dbe6dc] bg-white p-6 soft-shadow"><div className="flex items-center justify-between"><div><div className="font-mono-brand text-xs uppercase tracking-[0.16em] text-[#2c7e7c]">Referral tools</div><h2 className="mt-2 text-2xl font-semibold tracking-[-0.04em] text-[#163c3e]">Invite your learning circle.</h2></div><Link2 className="h-7 w-7 text-[#2c7e7c]" /></div><p className="mt-3 leading-7 text-[#607a7c]">Your link is personal. Qualified registrations are counted by the Academy, and your current position is shown below.</p><div className="mt-5 rounded-2xl border border-[#dce7dc] bg-[#f5f9f3] p-4"><div className="font-mono-brand text-xs text-[#2c7e7c]">{data?.referral.code ?? "Referral code pending"}</div><div className="mt-2 truncate text-sm text-[#507173]">{referralUrl || "Your link will be available after account setup."}</div></div><div className="mt-4 grid grid-cols-2 gap-3"><Button variant="outline" disabled={!referralUrl} onClick={copy} className="border-[#b9d0c5] text-[#1d5d5e]"><Copy className="mr-2 h-4 w-4" />Copy link</Button><Button disabled={!referralUrl} onClick={share} className="bg-[#123a3c] text-white hover:bg-[#214f50]"><Share2 className="mr-2 h-4 w-4" />Share</Button></div></div><div className="rounded-3xl bg-[#123a3c] p-6 text-white"><div className="flex items-start justify-between"><div><div className="font-mono-brand text-xs uppercase tracking-[0.16em] text-[#d4f36b]">Your verified impact</div><h2 className="mt-2 text-2xl font-semibold tracking-[-0.04em]">Keep it moving.</h2></div><Trophy className="h-8 w-8 text-[#d4f36b]" /></div><div className="mt-7 grid grid-cols-2 gap-3"><Metric value={data?.referral.qualifiedCount ?? 0} label="Qualified referrals" /><Metric value={data?.referral.leaderboardPosition ? `#${data.referral.leaderboardPosition}` : "—"} label="Leaderboard rank" /></div><Link href="/leaderboard" className="mt-5 inline-flex items-center text-sm font-semibold text-[#d4f36b]">View verified leaderboard <ExternalLink className="ml-2 h-4 w-4" /></Link></div></section>
    <section className="rounded-3xl border border-[#dbe6dc] bg-white p-6"><div className="flex items-center gap-3"><Award className="h-6 w-6 text-[#2c7e7c]" /><div><h2 className="text-xl font-semibold text-[#163c3e]">Certificates</h2><p className="text-sm text-[#6c8587]">Completion certificates appear here when course rules are met.</p></div></div>{data?.certificates.length ? <div className="mt-5 grid gap-3 md:grid-cols-2">{data.certificates.map((certificate) => <Link key={certificate.id} href={`/certificates/${certificate.certificateCode}`} className="rounded-2xl bg-[#f5f9f3] p-4 transition-colors hover:bg-[#ebf5e7]"><div className="font-semibold text-[#173d3f]">Certificate {certificate.certificateCode}</div><div className="mt-1 text-sm text-[#6c8587]">Issued {new Date(certificate.issuedAt).toLocaleDateString()} · View / print</div></Link>)}</div> : <p className="mt-5 rounded-2xl bg-[#f5f9f3] p-4 text-sm leading-6 text-[#607a7c]">No certificates are available yet. Complete your course lessons to become eligible.</p>}</section>
  </div></DashboardLayout>;
}
