import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, CheckCircle2, Circle, PlayCircle } from "lucide-react";
import { Link, useRoute } from "wouter";
import { toast } from "sonner";

export default function LessonPlayer() {
  const [, params] = useRoute("/learn/:courseId/:lessonId");
  const lessonId = Number(params?.lessonId ?? 0);
  const { isAuthenticated } = useAuth();
  const utils = trpc.useUtils();
  const { data, isLoading, error } = trpc.academy.getLessonDetail.useQuery({ lessonId }, { enabled: isAuthenticated && lessonId > 0 });
  const complete = trpc.academy.toggleLessonComplete.useMutation({ onSuccess: () => { utils.academy.getLessonDetail.invalidate({ lessonId }); utils.academy.getStudentDashboard.invalidate(); toast.success("Your lesson progress has been updated."); } });
  if (!isAuthenticated) return <div className="grid min-h-screen place-items-center bg-[#123a3c] p-6 text-center text-white"><div><h1 className="font-display text-4xl">Your lesson is waiting.</h1><Link href="/dashboard"><Button className="mt-5 bg-[#d4f36b] text-[#123a3c]">Sign in from your dashboard</Button></Link></div></div>;
  if (isLoading) return <div className="grid min-h-screen place-items-center bg-[#123a3c] text-white/70">Loading lesson…</div>;
  if (error || !data) return <div className="grid min-h-screen place-items-center bg-[#123a3c] p-6 text-center text-white"><div><h1 className="font-display text-4xl">This lesson is not available.</h1><p className="mt-3 text-white/65">You may need to enroll in the course first.</p><Link href="/dashboard"><Button className="mt-5 bg-[#d4f36b] text-[#123a3c]">Back to dashboard</Button></Link></div></div>;
  const { lesson } = data;
  return <div className="min-h-screen bg-[#102f31] text-white"><header className="border-b border-white/10 bg-[#123a3c]"><div className="container flex h-16 items-center justify-between"><Link href={`/courses/${params?.courseId ?? ""}`} className="inline-flex items-center text-sm font-medium text-white/70 hover:text-white"><ArrowLeft className="mr-2 h-4 w-4" />Course overview</Link><Link href="/dashboard" className="text-sm font-semibold text-[#d4f36b]">My learning</Link></div></header><main className="container grid gap-7 py-8 lg:grid-cols-[1fr_330px] lg:py-12"><div><div className="overflow-hidden rounded-3xl border border-white/10 bg-black shadow-2xl">{lesson.contentType === "video" && lesson.videoUrl ? <iframe src={lesson.videoUrl} title={lesson.title} className="aspect-video w-full" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen /> : <div className="grid aspect-video place-items-center bg-[#17494b]"><PlayCircle className="h-12 w-12 text-[#d4f36b]" /></div>}</div><div className="mt-8 max-w-3xl"><div className="font-mono-brand text-xs uppercase tracking-[0.18em] text-[#d4f36b]">Lesson {lesson.sortOrder}</div><h1 className="mt-3 font-display text-4xl leading-tight tracking-[-0.045em] sm:text-5xl">{lesson.title}</h1><div className="prose prose-invert mt-6 max-w-none prose-p:leading-8 prose-p:text-white/70" dangerouslySetInnerHTML={{ __html: lesson.contentHtml ?? "<p>This lesson’s learning notes will appear here.</p>" }} /></div></div><aside className="h-fit rounded-3xl border border-white/10 bg-white/[0.06] p-5 lg:sticky lg:top-6"><div className="text-sm font-semibold text-white">Lesson progress</div><div className="mt-4 flex items-center gap-3 rounded-2xl bg-white/[0.06] p-4">{data.completed ? <CheckCircle2 className="h-6 w-6 text-[#d4f36b]" /> : <Circle className="h-6 w-6 text-white/45" />}<div><div className="text-sm font-medium">{data.completed ? "Completed" : "In progress"}</div><div className="mt-0.5 text-xs text-white/55">{lesson.durationMinutes} minutes</div></div></div><Button onClick={() => complete.mutate({ lessonId, completed: !data.completed })} disabled={complete.isPending} className="mt-5 h-11 w-full bg-[#d4f36b] text-[#123a3c] hover:bg-[#c7e85c]">{complete.isPending ? "Saving…" : data.completed ? "Mark incomplete" : "Mark lesson complete"}</Button></aside></main></div>;
}
